name: TinyApp
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Check-out repository
        uses: actions/checkout@v2
        
      - name: Setup Node.js environment
        uses: actions/setup-node@v2.1.2
        
      - name: Install project dependencies
        run: npm install

      - name: Start project (or deploy command if needed)
        run: npm start
        
      - name: Github Pages
        uses: crazy-max/ghaction-github-pages@v2.1.3
        with:
          build_dir: .  # Set to your root directory if not using a dist folder
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
